# Generated by Django 3.1.7 on 2021-02-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepnotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaType', models.CharField(choices=[('img', 'IMAGE'), ('audio', 'AUDIO')], max_length=5)),
                ('value', models.CharField(max_length=255)),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepnotes.notes')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=255)),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepnotes.notes')),
            ],
        ),
    ]
