# Generated by Django 3.1.7 on 2021-02-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepnotes', '0004_auto_20210227_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='labelRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keepnotes.label'),
        ),
    ]
